image: ubuntu:20.04

stable-flashable:
  stage: deploy
  script:
    - apt update
    - apt install -y build-essential clang git img2simg jq sudo unzip wget xz-utils zlib1g-dev
    - git clone https://gitlab.com/ubports/community-ports/halium-generic-adaptation-build-tools build -b halium-11-mke2fs
    - DEVICE="$(source deviceinfo && echo $deviceinfo_codename)"
    - ./build/fetch-and-prepare-latest-ota.sh "16.04/arm64/android9/stable" "$DEVICE" ota
    - mkdir -p out
    - ./build/system-image-from-ota.sh ota/ubuntu_command out

    # create fastboot flashable super.img
    - git clone https://github.com/LonelyFool/lpunpack_and_lpmake.git
    - cd lpunpack_and_lpmake && ./make.sh && cd ..
    - wget https://volla.tech/filedump/ubuntu-touch-mimameid-firmware-r.tar.xz
    - tar xvJf ubuntu-touch-mimameid-firmware-r.tar.xz
    - ./lpunpack_and_lpmake/bin/lpmake --metadata-size 65536 --metadata-slots 2 --sparse --super-name super --device super:8589934592 --group ubuntu:8585740288 --partition system_a:none:7780433920:ubuntu --partition vendor_a:none:805306368:ubuntu --image 'system_a=out/system.img' --image 'vendor_a=partitions/vendor.img' --output out/super.img
  artifacts:
    paths:
      - out/boot.img
      - out/super.img
